# Generated by Django 5.2.9 on 2025-12-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_run_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее напоминание"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Чем пользователь должен себя вознаградить после выполнения",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
